version: '3.5'

networks:
  frontend:
  backend:

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ${WWW_PATH:?Define WWW_PATH}:/www
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - frontend
      - backend
  php:
    build: ./php
    restart: unless-stopped
#    user: ${PHP_USER_AND_GROUPID:?Define PHP_USER_AND_GROUPID} 
    volumes:
      - ${WWW_PATH:?Define WWW_PATH}:/www 
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: "172.17.0.1"
      PMA_ABSOLUTE_URI: "/phpmyadmin"
    networks:
      - frontend
  mariadb:
    image: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD:?Define MARIADB_PASSWORD}
    volumes:
      - ${MARIADB_PATH:?Define MARIADB_PATH}:/var/lib/mysql:rw
    networks:
      - frontend
      - backend

volumes:
  caddy_data:
    external: true
  caddy_config:
    external: true
