volumes:
  caddy_data:
    external: true
  caddy_config:
    external: true
  roundcube_storage:
    external: true
  grafana_storage:
    external: true
  prometheus_storage:
    external: true

services:
  # Caddy
  caddy:
    container_name: caddy
    image: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${TZ}:/etc/localtime
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - ${WWW_PATH}:/srv
      - caddy_data:/data
      - caddy_config:/config

  # PHP Preprocessor
  php:
    container_name: php
    build: ./build/php/
    restart: unless-stopped
    volumes:
      - ${TZ}:/etc/localtime
      - ${WWW_PATH}:/srv

  # Roundcube
  roundcube:
    container_name: roundcube
    image: roundcube/roundcubemail
    restart: unless-stopped
    volumes:
      - ${TZ}:/etc/localtime
      - roundcube_storage:/var/roundcube/db
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_DEFAULT_HOST=${RNDC_IMAP}
      - ROUNDCUBEMAIL_DEFAULT_PORT=${RNDC_IMAP_PORT}
      - ROUNDCUBEMAIL_SMTP_SERVER=${RNDC_SMTP}
      - ROUNDCUBEMAIL_SMTP_PORT=${RNDC_SMTP_PORT}
      - ROUNDCUBEMAIL_ASPELL_DICTS=${RNDC_DICTS}

  # MariaDB
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ${TZ}:/etc/localtime
      - ${DB_PATH}:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}

  # phpmyadmin
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: unless-stopped
    volumes:
      - ${TZ}:/etc/localtime
    environment:
      - PMA_HOST=mariadb
      - PMA_ABSOLUTE_URI=${PMA_URI}

  # Grafana
  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    restart: unless-stopped
    volumes:
      - ${TZ}:/etc/localtime
      - grafana_storage:/var/lib/grafana
      - ./config/grafana/custom.ini:/etc/grafana/grafana.ini:ro
    environment:
      - GF_SERVER_ROOT_URL=/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_FEATURE_TOGGLES_PUBLICDASHBOARDS=true

  # Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - ${TZ}:/etc/localtime
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_storage:/prometheus
