global:
  scrape_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: caddy
    static_configs:
      - targets: ['caddy:2019']
  - job_name: grafana
    metrics_path: /grafana/metrics
    static_configs:
      - targets: ['grafana:3000']
  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']
